procedure Final Project2 is
   raptor_prompt_variable_zzyz : Unbounded_String;
   line13 : ??_Variable;
   i0 : ??_Variable;
   line15 : ??_Variable;
   i1 : ??_Variable;
   i : ??_Variable;
   randnum4 : ??_Variable;
   i2 : ??_Variable;
   i3 : ??_Variable;
   minnum : ??_Variable;
   line14 : ??_Variable;
   randnum2 : ??_Variable;
   dishgreen_count : ??_Variable;
   randnum3 : ??_Variable;
   maxnum : ??_Variable;
   dishstarch_count : ??_Variable;
   line12 : ??_Variable;
   randnum : ??_Variable;
   dishmain_count : ??_Variable;
   line10 : ??_Variable;
   line11 : ??_Variable;
   line8 : ??_Variable;
   line9 : ??_Variable;
   i4 : ??_Variable;
   line1 : ??_Variable;
   line2 : ??_Variable;
   line3 : ??_Variable;
   line4 : ??_Variable;
   line5 : ??_Variable;
   line6 : ??_Variable;
   line7 : ??_Variable;
   dishmain : ??_1D_Array(1..??);
   dishstarch : ??_1D_Array(1..??);
   dishgreen : ??_1D_Array(1..??);
begin
   i :=0;
   i0 :=0;
   i1 :=0;
   i2 :=0;
   i3 :=0;
   i4 :=0;
   maxNum :=9;
   minNum :=0;
   dishMain_count :=0;
   redirect_input("dishMain.txt");
   loop
      dishMain_count :=dishMain_count+1;
      raptor_prompt_variable_zzyz :="DishMain";
      Put_Line(raptor_prompt_variable_zzyz);
      Get(dishMain(dishMain_count));
      i2 :=i2+1;
      exit when i2>=10;
   end loop;
   loop
      randNum :=Random*(maxNum-minNum)+1+minNum;
      randNum2 :=floor(randNum);
      i :=i+1;
      exit when i>=3;
   end loop;
   dishMain_count :=randNum2;
   dishGreen_count :=0;
   redirect_input("dishGreen.txt");
   loop
      dishGreen_count :=dishGreen_count+1;
      raptor_prompt_variable_zzyz :="DishGreen";
      Put_Line(raptor_prompt_variable_zzyz);
      Get(dishGreen(dishGreen_count));
      i4 :=i4+1;
      exit when i4>=10;
   end loop;
   loop
      randNum :=Random*(maxNum-minNum)+1+minNum;
      randNum3 :=floor(randNum);
      i0 :=i0+1;
      exit when i0>=3;
   end loop;
   dishGreen_count :=randNum3;
   dishStarch_count :=0;
   redirect_input("dishStarch.txt");
   loop
      dishStarch_count :=dishStarch_count+1;
      raptor_prompt_variable_zzyz :="DishStarch";
      Put_Line(raptor_prompt_variable_zzyz);
      Get(dishStarch(dishStarch_count));
      i3 :=i3+1;
      exit when i3>=10;
   end loop;
   loop
      randNum :=Random*(maxNum-minNum)+1+minNum;
      randNum4 :=floor(randNum);
      i0 :=i0+1;
      exit when i0>=3;
   end loop;
   dishStarch_count :=randNum4;
   Put_Line(" ");
   line1 :="   .-.__.-.__.-.";
   line2 :="  (             )        _______";
   line3 :="   )           (      .-' _____ '-.       /|";
   line4 :="  (       ||||  )   .' .-'.  ':'-. '.    | |  __";
   line5 :="   ) |||| |||| (   / .''::: .:    '. \   | | /  "";
   line6 :="  (  |||| \__/  ) / /   :::::'      \ \  | | |(_|";
   line7 :="   ) \__/  ||  ( | ;.    ':' `       ; | \ | \__/";
   line8 :="  (   ||   ||   )| |       '..       | |  ||  ||";
   line9 :="   )  ##   ##  ( | ; '      ::::.    ; |  ##  ##";
   line10 :="  (   ##   ##   ) \ \       '::::   / /   ##  ##";
   line11 :="   )  j#   ##  (   \ '.      :::  .' /    ##  ##";
   line12 :="  (   g#   ##   )   '. '-.___'_.-' .'     ##  ##";
   line13 :="   )  s#   ##  (      '-._______.-'       ##  ##";
   line14 :="  (   __   __   )";
   line15 :="   '-'  '-'  '-'";
   Put_Line(line1);
   Put_Line(line2);
   Put_Line(line3);
   Put_Line(line4);
   Put_Line(line5);
   Put_Line(line6);
   Put_Line(line7);
   Put_Line(line8);
   Put_Line(line9);
   Put_Line(line10);
   Put_Line(line11);
   Put_Line(line12);
   Put_Line(line13);
   Put_Line(line14);
   Put_Line(line15);
   Put_Line(" ");
   Put_Line("Today's Special is: "+dishMain(dishMain_count)+" "+dishGreen(dishGreen_count)+" "+dishStarch(dishStarch_count));
   Put_Line(" ");
   Put_Line(" ");
   Put_Line(" ");
   Put_Line(" ");
   i :=0;
end Final Project2;
