procedure Advanced_Hello_World is
   char12 : ??_Variable;
   char1 : ??_Variable;
   char2 : ??_Variable;
   char3 : ??_Variable;
   char4 : ??_Variable;
   char5 : ??_Variable;
   char6 : ??_Variable;
   char7 : ??_Variable;
   char10 : ??_Variable;
   char11 : ??_Variable;
   char8 : ??_Variable;
   char9 : ??_Variable;
   helloworld : ??_Variable;
begin
   char1 :="H";
   char2 :="e";
   char3 :="l";
   char4 :="l";
   char5 :="o";
   char6 :=" ";
   char7 :="W";
   char8 :="o";
   char9 :="r";
   char10 :="l";
   char11 :="d";
   char12 :="!";
   helloWorld :=char1+char2+char3+char4+char5+char6+char7+char8+char9+char10+char11+char12;
   Put(char1);
   Put(char2);
   Put(char3);
   Put(char4);
   Put(char5);
   Put(char6);
   Put(char7);
   Put(char8);
   Put(char9);
   Put(char10);
   Put(char11);
   Put_Line(char12);
   Put_Line(helloWorld);
end Advanced_Hello_World;
